defmodule CB.Render.Kb do
  @moduledoc """
  Render the belief graph as a set of markdown pages - one page per belief
  plus an index - forming a navigable knowledge base under `docs/kb/`.

  `build/1` is pure: beliefs in, `{relative_path, content}` pairs out, so the
  output is byte-stable for a given graph and the `--check` gate in
  `mix cb.generate.kb` can diff it against the committed tree. Nothing here
  reads a clock or the filesystem.

  Every dependency, dependent, and supersession link carries a one-sentence
  gloss of the target's claim, so a page satisfies the belief-reference
  protocol (cb:b597) on its own.
  """

  alias CB.Belief
  alias CB.Belief.Graph

  @header "<!-- Generated by mix cb.generate.kb from the belief graph. Do not edit; run the task to regenerate. -->"
  @gloss_limit 180

  @doc """
  Build the full page set for a list of beliefs.

  Returns a list of `{relative_path, content}` tuples, paths relative to the
  KB root (e.g. `"cb/b051.md"`, `"README.md"`), sorted by path.
  """
  def build(beliefs) do
    index = Graph.index(beliefs)
    dependents = dependents_map(beliefs)
    stale = Graph.stale(beliefs) |> Map.new(fn {b, bad} -> {b.id, bad} end)

    pages =
      Enum.map(beliefs, fn b ->
        {page_path(b.id), belief_page(b, index, dependents, stale)}
      end)

    [{"README.md", index_page(beliefs, stale)} | pages]
    |> Enum.sort_by(&elem(&1, 0))
  end

  @doc "Relative page path for a belief id, e.g. `cb:b051` -> `cb/b051.md`."
  def page_path(id) do
    {ns, local} = split_id(id)
    "#{ns}/#{local}.md"
  end

  @doc """
  One-sentence gloss of a belief's claim, truncated to #{@gloss_limit}
  characters. Used as the summary that rides along with every id link.
  """
  def gloss(%Belief{claim: claim}), do: gloss(claim)
  def gloss(nil), do: ""

  def gloss(claim) when is_binary(claim) do
    first =
      case String.split(claim, ~r/(?<=[.!?]) /, parts: 2) do
        [sentence | _] -> sentence
      end

    if String.length(first) > @gloss_limit do
      String.slice(first, 0, @gloss_limit) <> "..."
    else
      first
    end
  end

  # -- belief pages ----------------------------------------------------------

  defp belief_page(b, index, dependents, stale) do
    [
      @header,
      "",
      "# #{b.id}#{name_suffix(b)}",
      "",
      "> #{b.claim}",
      "",
      meta_block(b),
      artifact_block(b),
      rules_block(b),
      evidence_block(b),
      deps_block(b, index),
      dependents_block(b, index, dependents),
      subjects_block(b),
      history_block(b, index),
      stale_block(b, index, stale),
      materialized_block(b),
      "[Index](../README.md)",
      ""
    ]
    |> List.flatten()
    |> Enum.join("\n")
  end

  defp name_suffix(%Belief{name: name}) when is_binary(name) and name != "", do: " · #{name}"
  defp name_suffix(_), do: ""

  defp meta_block(b) do
    type = Belief.normalize_type(b.type)
    grade = if Belief.contract?(b), do: " (contract-grade)", else: ""

    line =
      ["**Type:** #{type}#{grade}", "**Kind:** #{b.kind}", "**Domain:** #{b.domain}", "**Status:** #{status_text(b)}"]
      |> Enum.join(" · ")

    tags =
      case b.tags do
        [] -> []
        tags -> ["**Tags:** " <> Enum.map_join(tags, ", ", &"`#{&1}`")]
      end

    created = if b.created, do: ["**Created:** #{b.created}"], else: []
    who = if b.who, do: ["**Who:** #{b.who}"], else: []

    [line] ++ tags ++ created ++ who ++ [""]
  end

  defp status_text(%Belief{status: "superseded", superseded_by: by}) when is_binary(by),
    do: "superseded"

  defp status_text(%Belief{status: "retracted", retracted_on: on}) when is_binary(on),
    do: "retracted #{on}"

  defp status_text(%Belief{status: status}), do: status || "-"

  defp artifact_block(%Belief{artifact: nil}), do: []

  defp artifact_block(%Belief{artifact: artifact}) do
    ["**Artifact:** #{artifact_link(artifact)}", ""]
  end

  # A page lives at <root>/<ns>/<id>.md, so the repo root is ../../ up from it.
  defp artifact_link("document:" <> path), do: "[`document:#{path}`](../../../#{path})"

  defp artifact_link("code:" <> rest) do
    path = rest |> String.split("#", parts: 2) |> hd()
    "[`code:#{rest}`](../../../#{path})"
  end

  defp artifact_link(other), do: "`#{other}`"

  defp rules_block(%Belief{rules: [], invariants: []}), do: []

  defp rules_block(%Belief{rules: rules, invariants: invariants}) do
    inv =
      case invariants do
        [] -> []
        list -> ["## Invariants", "" | Enum.map(list, &"- #{&1}")] ++ [""]
      end

    r =
      case rules do
        [] ->
          []

        list ->
          ["## Rules", "", "```json", encode_rules(list), "```", ""]
      end

    inv ++ r
  end

  defp encode_rules(rules), do: Enum.map_join(rules, "\n", &Jason.encode!(&1, pretty: true))

  defp evidence_block(%Belief{evidence: []}), do: []

  defp evidence_block(%Belief{evidence: evidence}) do
    entries =
      evidence
      |> Enum.with_index(1)
      |> Enum.flat_map(fn {e, i} ->
        date = Map.get(e, "date", "-")
        detail = Map.get(e, "detail", "")
        artifact = Map.get(e, "artifact")

        ["#{i}. **#{date}** - #{detail}"] ++
          if artifact, do: ["   - artifact: #{artifact_link(artifact)}"], else: []
      end)

    ["## Evidence", "" | entries] ++ [""]
  end

  defp deps_block(%Belief{deps: []}, _index), do: []

  defp deps_block(%Belief{deps: deps} = b, index) do
    ["## Depends on", "" | Enum.map(deps, &id_link_line(&1, b.id, index))] ++ [""]
  end

  defp dependents_block(b, index, dependents) do
    case Map.get(dependents, b.id, []) do
      [] ->
        []

      ids ->
        ["## Depended on by", "" | ids |> sort_ids() |> Enum.map(&id_link_line(&1, b.id, index))] ++
          [""]
    end
  end

  defp subjects_block(%Belief{subjects: []}), do: []

  defp subjects_block(%Belief{subjects: subjects}) do
    lines =
      Enum.map(subjects, fn s ->
        "- `#{Map.get(s, "ref", "-")}` (#{Map.get(s, "type", "-")})"
      end)

    ["## Subjects", "" | lines] ++ [""]
  end

  defp history_block(b, index) do
    predecessors =
      index
      |> Map.values()
      |> Enum.filter(&(&1.superseded_by == b.id))
      |> Enum.map(& &1.id)
      |> sort_ids()

    successor =
      case b.superseded_by do
        nil -> []
        by -> ["- Superseded by #{id_link(by, b.id, index)}"]
      end

    retraction =
      case b.retracted_reason do
        nil -> []
        reason -> ["- Retracted#{if b.retracted_on, do: " " <> b.retracted_on, else: ""}: #{reason}"]
      end

    pred_lines = Enum.map(predecessors, &("- Supersedes " <> id_link(&1, b.id, index)))

    case pred_lines ++ successor ++ retraction do
      [] -> []
      lines -> ["## History", "" | lines] ++ [""]
    end
  end

  defp stale_block(b, index, stale) do
    case Map.get(stale, b.id) do
      nil ->
        []

      bad ->
        lines = Enum.map(sort_ids(bad), &("- " <> id_link(&1, b.id, index)))
        ["## Stale", "", "Rests on superseded or retracted deps:", "" | lines] ++ [""]
    end
  end

  defp materialized_block(%Belief{materialized: %{} = m}) when map_size(m) > 0 do
    date = Map.get(m, "date", "-")
    tasks = m |> Map.get("tasks", []) |> Enum.map_join(", ", &"`#{&1}`")
    ["**Materialized:** #{date}#{if tasks != "", do: " (#{tasks})", else: ""}", ""]
  end

  defp materialized_block(_), do: []

  # -- index page ------------------------------------------------------------

  defp index_page(beliefs, stale) do
    by_status = Enum.group_by(beliefs, & &1.status)
    active = by_status |> Map.get("active", []) |> sort_beliefs()
    inactive = ((by_status["superseded"] || []) ++ (by_status["retracted"] || [])) |> sort_beliefs()

    counts =
      active
      |> Enum.group_by(&Belief.normalize_type(&1.type))
      |> Enum.map(fn {t, list} -> {t, length(list)} end)
      |> Enum.sort()
      |> Enum.map_join(", ", fn {t, n} -> "#{n} #{t}" end)

    type_sections =
      for type <- ~w(attestation aggregation inference prescription),
          section = Map.get(Enum.group_by(active, &Belief.normalize_type(&1.type)), type, []),
          section != [] do
        ["## #{String.capitalize(type)}s (#{length(section)})", "" | Enum.map(section, &index_line/1)] ++
          [""]
      end

    contracts = Enum.filter(active, &Belief.contract?/1)

    contract_section =
      case contracts do
        [] -> []
        list -> ["## Contracts (#{length(list)})", "" | Enum.map(list, &index_line/1)] ++ [""]
      end

    stale_section =
      case sort_ids(Map.keys(stale)) do
        [] ->
          []

        ids ->
          lines = Enum.map(ids, fn id -> "- [#{id}](#{page_path(id)})" end)
          ["## Stale (#{length(ids)})", "", "Active beliefs resting on superseded or retracted deps:", "" | lines] ++ [""]
      end

    inactive_section =
      case inactive do
        [] ->
          []

        list ->
          entries =
            Enum.map(list, fn b ->
              arrow = if b.superseded_by, do: " -> [#{b.superseded_by}](#{page_path(b.superseded_by)})", else: ""
              "- [#{b.id}](#{page_path(b.id)}) (#{b.status})#{arrow}"
            end)

          ["## Superseded and retracted (#{length(list)})", "", "<details><summary>Show</summary>", "" | entries] ++
            ["", "</details>", ""]
      end

    ([
       @header,
       "",
       "# Belief knowledge base",
       "",
       "One page per belief, generated from the graph by `mix cb.generate.kb` and gated fresh in CI by `--check`. Links between pages follow `deps` (derivation), reverse deps, and supersession; every link carries a one-sentence gloss of the target's claim (cb:b597, the belief-reference protocol).",
       "",
       "Active: #{length(active)} (#{counts}). Total nodes: #{length(beliefs)}.",
       ""
     ] ++
       List.flatten(type_sections) ++
       List.flatten(contract_section) ++
       List.flatten(stale_section) ++ List.flatten(inactive_section))
    |> Enum.join("\n")
  end

  defp index_line(b) do
    grade = if Belief.contract?(b), do: " [contract]", else: ""
    "- [#{b.id}](#{page_path(b.id)})#{grade} - #{gloss(b)}"
  end

  # -- link helpers ----------------------------------------------------------

  defp id_link_line(id, from_id, index) do
    case Graph.lookup(index, id) do
      nil -> "- `#{id}` (unresolved)"
      target -> "- #{id_link(id, from_id, index)} - #{gloss(target)}#{status_marker(target)}"
    end
  end

  defp status_marker(%Belief{status: "active"}), do: ""
  defp status_marker(%Belief{status: status}), do: " *(#{status})*"

  defp id_link(id, from_id, index) do
    case Graph.lookup(index, id) do
      nil ->
        "`#{id}`"

      _ ->
        {from_ns, _} = split_id(from_id)
        {ns, local} = split_id(id)
        href = if ns == from_ns, do: "#{local}.md", else: "../#{ns}/#{local}.md"
        "[#{id}](#{href})"
    end
  end

  defp dependents_map(beliefs) do
    beliefs
    |> Enum.flat_map(fn b -> Enum.map(b.deps || [], &{&1, b.id}) end)
    |> Enum.group_by(&elem(&1, 0), &elem(&1, 1))
  end

  defp split_id(id) do
    case String.split(id, ":", parts: 2) do
      [ns, local] -> {ns, local}
      [local] -> {"_", local}
    end
  end

  defp sort_beliefs(beliefs), do: Enum.sort_by(beliefs, &id_sort_key(&1.id))
  defp sort_ids(ids), do: Enum.sort_by(ids, &id_sort_key/1)

  # Sort b2 before b10: split the local id into its alpha prefix and number.
  defp id_sort_key(id) do
    {ns, local} = split_id(id)

    case Regex.run(~r/^([a-z-]*)(\d*)(.*)$/, local) do
      [_, prefix, "", rest] -> {ns, prefix, 0, rest}
      [_, prefix, digits, rest] -> {ns, prefix, String.to_integer(digits), rest}
      _ -> {ns, local, 0, ""}
    end
  end
end
