defmodule CB.Render.KbTest do
  use ExUnit.Case, async: true

  alias CB.Belief
  alias CB.Render.Kb

  defp fixture do
    [
      %{
        "id" => "cb:b1",
        "type" => "attestation",
        "kind" => "observation",
        "domain" => "dev",
        "tags" => ["fixture"],
        "claim" => "Source one said the sky was green on Tuesday. A second sentence that should be trimmed from the gloss.",
        "artifact" => "document:docs/reference.md",
        "evidence" => [
          %{"date" => "2026-07-01", "detail" => "What the source said.", "artifact" => "document:docs/reference.md"}
        ],
        "subjects" => [%{"ref" => "sky", "type" => "entity"}],
        "deps" => [],
        "status" => "active",
        "created" => "2026-07-01"
      },
      %{
        "id" => "cb:b2",
        "type" => "inference",
        "kind" => "design-observation",
        "domain" => "dev",
        "tags" => [],
        "claim" => "The sky tends green early in the week.",
        "evidence" => [],
        "subjects" => [],
        "deps" => ["cb:b1"],
        "status" => "active",
        "created" => "2026-07-02"
      },
      %{
        "id" => "cb:b3",
        "type" => "prescription",
        "kind" => "convention",
        "domain" => "dev",
        "tags" => ["house"],
        "claim" => "Carry an umbrella on Tuesdays.",
        "invariants" => ["An umbrella is carried"],
        "artifact" => "user:test:2026-07-03",
        "evidence" => [],
        "subjects" => [],
        "deps" => ["cb:b2"],
        "status" => "superseded",
        "superseded_by" => "cb:b10",
        "created" => "2026-07-03"
      },
      %{
        "id" => "cb:b10",
        "type" => "prescription",
        "kind" => "convention",
        "domain" => "dev",
        "tags" => ["house"],
        "claim" => "Carry an umbrella every day.",
        "invariants" => ["An umbrella is carried"],
        "artifact" => "user:test:2026-07-04",
        "evidence" => [],
        "subjects" => [],
        "deps" => ["cb:b2"],
        "status" => "active",
        "created" => "2026-07-04"
      },
      %{
        "id" => "cb:b4",
        "type" => "inference",
        "kind" => "design-observation",
        "domain" => "dev",
        "tags" => [],
        "claim" => "Rests on a superseded premise.",
        "evidence" => [],
        "subjects" => [],
        "deps" => ["cb:b3"],
        "status" => "active",
        "created" => "2026-07-05"
      }
    ]
    |> Enum.map(&Belief.from_map/1)
  end

  defp pages, do: Map.new(Kb.build(fixture()))

  test "builds one page per belief plus an index" do
    built = pages()

    assert Map.has_key?(built, "README.md")
    assert Map.has_key?(built, "cb/b1.md")
    assert Map.has_key?(built, "cb/b10.md")
    assert map_size(built) == length(fixture()) + 1
  end

  test "output is deterministic" do
    assert Kb.build(fixture()) == Kb.build(fixture())
  end

  test "dep links carry a one-sentence gloss of the target's claim" do
    page = pages()["cb/b2.md"]

    assert page =~ "## Depends on"
    assert page =~ "[cb:b1](b1.md) - Source one said the sky was green on Tuesday."
    refute page =~ "trimmed from the gloss"
  end

  test "reverse edges render as depended-on-by links" do
    page = pages()["cb/b1.md"]

    assert page =~ "## Depended on by"
    assert page =~ "[cb:b2](b2.md)"
  end

  test "supersession links both directions" do
    assert pages()["cb/b3.md"] =~ "- Superseded by [cb:b10](b10.md)"
    assert pages()["cb/b10.md"] =~ "- Supersedes [cb:b3](b3.md)"
  end

  test "a belief resting on a superseded dep wears a stale section" do
    page = pages()["cb/b4.md"]

    assert page =~ "## Stale"
    assert page =~ "[cb:b3](b3.md)"
    refute pages()["cb/b2.md"] =~ "## Stale"
  end

  test "document artifacts link into the repo" do
    assert pages()["cb/b1.md"] =~ "[`document:docs/reference.md`](../../../docs/reference.md)"
  end

  test "contract-grade beliefs render invariants and are indexed as contracts" do
    assert pages()["cb/b10.md"] =~ "## Invariants"
    assert pages()["README.md"] =~ "## Contracts (1)"
  end

  test "index lists active beliefs by type with glosses and ids sort numerically" do
    index = pages()["README.md"]

    assert index =~ "## Attestations (1)"
    assert index =~ "[cb:b1](cb/b1.md) - Source one said the sky was green on Tuesday."
    assert index =~ "(superseded) -> [cb:b10](cb/b10.md)"

    # b3 sorts before b10 in the inactive section despite string order
    assert index =~ "## Superseded and retracted (1)"
  end

  test "every page carries the generated header" do
    assert Enum.all?(pages(), fn {_, content} ->
             String.starts_with?(content, "<!-- Generated by mix cb.generate.kb")
           end)
  end
end
